// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Chaser.Data.Migrations
{
    [DbContext(typeof(ChaserDbContext))]
    [Migration("20230731111740_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Chaser.Data.Moderator", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("IdentityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Moderators");
                });

            modelBuilder.Entity("Chaser.Data.Scammer", b =>
                {
                    b.Property<ulong>("Id")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("BanReason")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("IdentityAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("IdentityByUserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ProofsImageUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Scammers");
                });
#pragma warning restore 612, 618
        }
    }
}
